import type {
  ModelCatalog,
  ModelCatalogEntry,
} from "@posthog/shared/agent-platform-types";

/**
 * The served-model catalog for the model browser + auto-level preview.
 *
 * STAND-IN: this is a snapshot of the live ai-gateway `/v1/models` catalog. When
 * the catalog endpoint lands (e.g. `GET …/agent_applications/models`), replace
 * the body with a real query — `ModelCatalog` already matches the wire shape, so
 * nothing downstream changes.
 */
const MODELS: ModelCatalogEntry[] = [
  {
    model: "anthropic/claude-haiku-4.5",
    provider: "anthropic",
    context_window: 200000,
    input: 1.0,
    output: 5.0,
    cacheRead: 0.1,
    cacheWrite: 1.25,
  },
  {
    model: "anthropic/claude-opus-4.1",
    provider: "anthropic",
    context_window: 200000,
    input: 15.0,
    output: 75.0,
    cacheRead: 1.5,
    cacheWrite: 18.75,
  },
  {
    model: "anthropic/claude-opus-4.5",
    provider: "anthropic",
    context_window: 200000,
    input: 5.0,
    output: 25.0,
    cacheRead: 0.5,
    cacheWrite: 6.25,
  },
  {
    model: "anthropic/claude-opus-4.6",
    provider: "anthropic",
    context_window: 1000000,
    input: 5.0,
    output: 25.0,
    cacheRead: 0.5,
    cacheWrite: 6.25,
  },
  {
    model: "anthropic/claude-opus-4.7",
    provider: "anthropic",
    context_window: 1000000,
    input: 5.0,
    output: 25.0,
    cacheRead: 0.5,
    cacheWrite: 6.25,
  },
  {
    model: "anthropic/claude-opus-4.8",
    provider: "anthropic",
    context_window: 1000000,
    input: 5.0,
    output: 25.0,
    cacheRead: 0.5,
    cacheWrite: 6.25,
  },
  {
    model: "anthropic/claude-sonnet-4.5",
    provider: "anthropic",
    context_window: 1000000,
    input: 3.0,
    output: 15.0,
    cacheRead: 0.3,
    cacheWrite: 3.75,
  },
  {
    model: "anthropic/claude-sonnet-4.6",
    provider: "anthropic",
    context_window: 1000000,
    input: 3.0,
    output: 15.0,
    cacheRead: 0.3,
    cacheWrite: 3.75,
  },
  {
    model: "openai/gpt-3.5-turbo",
    provider: "openai",
    context_window: 16385,
    input: 0.5,
    output: 1.5,
  },
  {
    model: "openai/gpt-3.5-turbo-16k",
    provider: "openai",
    context_window: 16385,
    input: 3.0,
    output: 4.0,
  },
  {
    model: "openai/gpt-3.5-turbo-instruct",
    provider: "openai",
    context_window: 4095,
    input: 1.5,
    output: 2.0,
  },
  {
    model: "openai/gpt-4",
    provider: "openai",
    context_window: 8191,
    input: 30.0,
    output: 60.0,
  },
  {
    model: "openai/gpt-4-turbo",
    provider: "openai",
    context_window: 128000,
    input: 10.0,
    output: 30.0,
  },
  {
    model: "openai/gpt-4.1",
    provider: "openai",
    context_window: 1047576,
    input: 2.0,
    output: 8.0,
    cacheRead: 0.5,
  },
  {
    model: "openai/gpt-4.1-mini",
    provider: "openai",
    context_window: 1047576,
    input: 0.4,
    output: 1.6,
    cacheRead: 0.1,
  },
  {
    model: "openai/gpt-4.1-nano",
    provider: "openai",
    context_window: 1047576,
    input: 0.1,
    output: 0.4,
    cacheRead: 0.025,
  },
  {
    model: "openai/gpt-4o",
    provider: "openai",
    context_window: 128000,
    input: 2.5,
    output: 10.0,
    cacheRead: 1.25,
  },
  {
    model: "openai/gpt-4o-2024-05-13",
    provider: "openai",
    context_window: 128000,
    input: 5.0,
    output: 15.0,
  },
  {
    model: "openai/gpt-4o-2024-08-06",
    provider: "openai",
    context_window: 128000,
    input: 2.5,
    output: 10.0,
    cacheRead: 1.25,
  },
  {
    model: "openai/gpt-4o-2024-11-20",
    provider: "openai",
    context_window: 128000,
    input: 2.5,
    output: 10.0,
    cacheRead: 1.25,
  },
  {
    model: "openai/gpt-4o-mini",
    provider: "openai",
    context_window: 128000,
    input: 0.15,
    output: 0.6,
    cacheRead: 0.075,
  },
  {
    model: "openai/gpt-4o-mini-2024-07-18",
    provider: "openai",
    context_window: 128000,
    input: 0.15,
    output: 0.6,
    cacheRead: 0.075,
  },
  {
    model: "openai/gpt-4o-mini-search-preview",
    provider: "openai",
    context_window: 128000,
    input: 0.15,
    output: 0.6,
  },
  {
    model: "openai/gpt-4o-search-preview",
    provider: "openai",
    context_window: 128000,
    input: 2.5,
    output: 10.0,
  },
  {
    model: "openai/gpt-5",
    provider: "openai",
    context_window: 400000,
    input: 1.25,
    output: 10.0,
    cacheRead: 0.125,
  },
  {
    model: "openai/gpt-5-codex",
    provider: "openai",
    context_window: 400000,
    input: 1.25,
    output: 10.0,
    cacheRead: 0.125,
  },
  {
    model: "openai/gpt-5-mini",
    provider: "openai",
    context_window: 400000,
    input: 0.25,
    output: 2.0,
    cacheRead: 0.025,
  },
  {
    model: "openai/gpt-5-nano",
    provider: "openai",
    context_window: 400000,
    input: 0.05,
    output: 0.4,
    cacheRead: 0.005,
  },
  {
    model: "openai/gpt-5-pro",
    provider: "openai",
    context_window: 400000,
    input: 15.0,
    output: 120.0,
  },
  {
    model: "openai/gpt-5.1",
    provider: "openai",
    context_window: 400000,
    input: 1.25,
    output: 10.0,
    cacheRead: 0.125,
  },
  {
    model: "openai/gpt-5.1-codex",
    provider: "openai",
    context_window: 400000,
    input: 1.25,
    output: 10.0,
    cacheRead: 0.125,
  },
  {
    model: "openai/gpt-5.1-codex-max",
    provider: "openai",
    context_window: 400000,
    input: 1.25,
    output: 10.0,
    cacheRead: 0.125,
  },
  {
    model: "openai/gpt-5.1-codex-mini",
    provider: "openai",
    context_window: 400000,
    input: 0.25,
    output: 2.0,
    cacheRead: 0.025,
  },
  {
    model: "openai/gpt-5.2",
    provider: "openai",
    context_window: 400000,
    input: 1.75,
    output: 14.0,
    cacheRead: 0.175,
  },
  {
    model: "openai/gpt-5.2-codex",
    provider: "openai",
    context_window: 400000,
    input: 1.75,
    output: 14.0,
    cacheRead: 0.175,
  },
  {
    model: "openai/gpt-5.2-pro",
    provider: "openai",
    context_window: 400000,
    input: 21.0,
    output: 168.0,
  },
  {
    model: "openai/gpt-5.3-codex",
    provider: "openai",
    context_window: 400000,
    input: 1.75,
    output: 14.0,
    cacheRead: 0.175,
  },
  {
    model: "openai/gpt-5.4",
    provider: "openai",
    context_window: 1050000,
    input: 2.5,
    output: 15.0,
    cacheRead: 0.25,
  },
  {
    model: "openai/gpt-5.4-mini",
    provider: "openai",
    context_window: 400000,
    input: 0.75,
    output: 4.5,
    cacheRead: 0.075,
  },
  {
    model: "openai/gpt-5.4-nano",
    provider: "openai",
    context_window: 400000,
    input: 0.2,
    output: 1.25,
    cacheRead: 0.02,
  },
  {
    model: "openai/gpt-5.4-pro",
    provider: "openai",
    context_window: 1050000,
    input: 30.0,
    output: 180.0,
  },
  {
    model: "openai/gpt-5.5",
    provider: "openai",
    context_window: 1050000,
    input: 5.0,
    output: 30.0,
    cacheRead: 0.5,
  },
  {
    model: "openai/gpt-5.5-pro",
    provider: "openai",
    context_window: 1050000,
    input: 30.0,
    output: 180.0,
  },
  {
    model: "openai/gpt-audio",
    provider: "openai",
    context_window: 128000,
    input: 2.5,
    output: 10.0,
  },
  {
    model: "openai/gpt-audio-mini",
    provider: "openai",
    context_window: 128000,
    input: 0.6,
    output: 2.4,
  },
  {
    model: "openai/o1",
    provider: "openai",
    context_window: 200000,
    input: 15.0,
    output: 60.0,
    cacheRead: 7.5,
  },
  {
    model: "openai/o1-pro",
    provider: "openai",
    context_window: 200000,
    input: 150.0,
    output: 600.0,
  },
  {
    model: "openai/o3",
    provider: "openai",
    context_window: 200000,
    input: 2.0,
    output: 8.0,
    cacheRead: 0.5,
  },
  {
    model: "openai/o3-deep-research",
    provider: "openai",
    context_window: 200000,
    input: 10.0,
    output: 40.0,
    cacheRead: 2.5,
  },
  {
    model: "openai/o3-mini",
    provider: "openai",
    context_window: 200000,
    input: 1.1,
    output: 4.4,
    cacheRead: 0.55,
  },
  {
    model: "openai/o3-pro",
    provider: "openai",
    context_window: 200000,
    input: 20.0,
    output: 80.0,
  },
  {
    model: "openai/o4-mini",
    provider: "openai",
    context_window: 200000,
    input: 1.1,
    output: 4.4,
    cacheRead: 0.275,
  },
  {
    model: "openai/o4-mini-deep-research",
    provider: "openai",
    context_window: 200000,
    input: 2.0,
    output: 8.0,
    cacheRead: 0.5,
  },
];

// Curated auto levels → canonical ids in priority order. Mirrors the backend's
// MODEL_POLICY_LEVELS (resolved to the catalog's canonical ids).
const LEVELS: ModelCatalog["levels"] = {
  low: ["anthropic/claude-haiku-4.5", "openai/gpt-5-mini"],
  medium: ["anthropic/claude-sonnet-4.6", "openai/gpt-5"],
  high: ["anthropic/claude-opus-4.7", "openai/gpt-5-pro"],
};

export function useModelCatalog(): {
  catalog: ModelCatalog;
  isLoading: boolean;
} {
  return { catalog: { models: MODELS, levels: LEVELS }, isLoading: false };
}
