import { useDashboardEditStore } from "@features/canvas/stores/dashboardEditStore";
import type { Spec } from "@json-render/react";
import type {
  DashboardRecord,
  DashboardSummary,
} from "@main/services/dashboards/schemas";
import { useTRPC } from "@renderer/trpc/client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "@tanstack/react-router";
import { useCallback } from "react";

/** List of saved dashboards (file-backed, generated by json-render). */
export function useDashboards(): {
  dashboards: DashboardSummary[];
  isLoading: boolean;
} {
  const trpc = useTRPC();
  const { data, isLoading } = useQuery(
    trpc.dashboards.list.queryOptions(undefined, { staleTime: 5_000 }),
  );
  return { dashboards: data ?? [], isLoading };
}

/** A single saved dashboard record (spec + metadata). */
export function useDashboard(id: string | undefined): {
  dashboard: DashboardRecord | null | undefined;
  isLoading: boolean;
} {
  const trpc = useTRPC();
  const { data, isLoading } = useQuery(
    trpc.dashboards.get.queryOptions(
      { id: id ?? "" },
      { enabled: !!id, staleTime: 5_000 },
    ),
  );
  return { dashboard: data, isLoading };
}

/** Save (update) + fork (create) mutations, invalidating the list + record. */
export function useDashboardMutations() {
  const trpc = useTRPC();
  const queryClient = useQueryClient();

  const invalidate = () => {
    void queryClient.invalidateQueries(trpc.dashboards.list.pathFilter());
    void queryClient.invalidateQueries(trpc.dashboards.get.pathFilter());
  };

  const save = useMutation(
    trpc.dashboards.update.mutationOptions({ onSuccess: invalidate }),
  );
  const create = useMutation(
    trpc.dashboards.create.mutationOptions({ onSuccess: invalidate }),
  );

  return {
    saveDashboard: (id: string, spec: Spec | null, name?: string) =>
      save.mutateAsync({
        id,
        spec: spec as Record<string, unknown> | null,
        name,
      }),
    createDashboard: (name: string, spec: Spec | null) =>
      create.mutateAsync({
        name,
        spec: spec as Record<string, unknown> | null,
      }),
    isSaving: save.isPending,
    isCreating: create.isPending,
  };
}

/** Create a blank dashboard, enter edit mode, and navigate to it. */
export function useCreateAndOpenDashboard(): (name?: string) => Promise<void> {
  const navigate = useNavigate();
  const { createDashboard } = useDashboardMutations();
  const setEditing = useDashboardEditStore((s) => s.setEditing);

  return useCallback(
    async (name = "Untitled dashboard") => {
      const record = await createDashboard(name, null);
      setEditing(record.id, true);
      void navigate({
        to: "/website/dashboards/$dashboardId",
        params: { dashboardId: record.id },
      });
    },
    [createDashboard, navigate, setEditing],
  );
}
